### ISSUE TITLE
EPIC: Create a Schedule placeholder in Nav, with the new Scedule component

### ISSUE THREAD

**Issue by Ononymous** [ucsb-cs156-s24/proj-gauchoride-s24-5pm-5#33]
- As a user
- I can select the Schedule page and see the Scheduler
- So that it can lead to next issue to add more components into the Schedule

<img width="1253" alt="image" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/36137654/9d54491a-7d92-4982-a338-e87c75852e76">

Acceptance Criteria
- [x] A logged in user can see and select the Schedule page from navbar
- [x] The page contains the new Schedule placeholder component
- [x] The Schedule component should have basic table elements such as `Monday`, `Tuesday`, and time from `7am` to `9pm`
